apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-service
spec:
  type: LoadBalancer
  selector:
      app: kafka-broker
  ports:
  - name: tcp
    port: 9092
    targetPort: 9092
    protocol: TCP