apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-deployment
  labels:
    app: kafka-broker
spec:
  selector:
    matchLabels: 
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      initContainers:
        - name: init-kafka-broker
          image: busybox
          command: ['sh','-c','echo Waiting for Zookeeper Host']
      containers:
        - name: my-test
          image: busybox
        - name: kafka-broker
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: localhost
            - name : KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181
