apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-deployment
  labels:
    app: kafka-broker
spec:
  selector:
    matchLabels: 
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper
          ports:
            - containerPort: 2181
        - name: kafka-broker
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: localhost
            - name : KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181
