---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-system-deployment
  labels:
    app: message-system
spec:
  selector:
    matchLabels: 
      app: message-system
  template:
    metadata:
      labels:
        app: message-system
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper
          ports:
            - containerPort: 2181
        - name: kafka-broker
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: localhost
            - name : KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181

---

apiVersion: v1
kind: Service
metadata:
  name: message-system-service
  labels:
    app: message-system-service
spec:
  type: LoadBalancer
  selector:
      app: message-system
  ports:
  - name: tcp
    port: 9092
    targetPort: 9092
    protocol: TCP

