---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-console-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/test

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-console-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: my-console-pv
