apiVersion: v1
kind: Service
metadata:
  name: my-console-service
  labels:
    app: my-console-service
spec:
  type: LoadBalancer
  selector:
      app: my-console
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP