apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  type: LoadBalancer
  selector:
      app: zookeeper
  ports:
  - name: tcp
    port: 2181
    targetPort: 2181
    protocol: TCP